### PR TITLE
bumping gem dependency specs

### PR DESCRIPTION
**Pull request by matheuseduardo**
I also:
- updated bootstrap url to latest version (4.5.2 ~> 4.6);
- created an option to include bootstrap scripts after footer;

I think would be a good "upgrade" to the theme! ;)

_(my english is terrible, feel free to make any necessary spelling corrections)_

### CODE REVIEW

**Comment by matheuseduardo** [comment]
I forgot tests "details".

I made the change, and tried all pages and posts.
I didn't see any changes for design/layout.. so seems to be working fine.

**Review by aterenin — CHANGES_REQUESTED** [review]
Thanks for the PR and confirming everything still works with Bootstrap 4.6 with no class renaming or other HTML changes needed!

Regarding `include_bsscripts`: I prefer to wait until Bootstrap 5.0 to add this option, because at that time it will no longer depend on JQuery which will make it simpler to load everything asynchronously within the head file. This ensures that if the user overrides the footer include to change the page design for their purposes, but still has this option enabled, then the JavaScript file is still loaded. Therefore, please leave this out of the PR for now, but also please feel free and encouraged to make an issue once 5.0 is out of beta!

**Comment by matheuseduardo** [comment]
I made the change back, but I don't know how to request again, if needed.
best regards

**Review by aterenin — APPROVED** [review]

**Comment by aterenin** [comment]
Thanks again for the PR!

**Comment by matheuseduardo** [comment]
Thank you! Do you know how much time to update [ruby gem](https://rubygems.org/gems/minima-reboot)?
Is it an automated process?

**Comment by aterenin** [comment]
Just set up a GitHub action in order to do that without cloning the repo and building manually as I've typically done in the past - should land on RubyGems any minute.

**Pull request merged**
